// src/components/charts/CategoryChart.vue
<template>
  <div v-if="hasCategories">
    <VueDataUi component="VueUiDonut" :dataset="chartData" :config="config" />
  </div>
  <div v-else class="no-data">
    <p>No expense categories found</p>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { VueDataUi } from 'vue-data-ui';
import { useChartConfigs, COLORS } from '../../composables/useChartConfigs.js';

const props = defineProps({
  data: {
    type: Object,
    required: true
  }
});

const { getCategoryConfig } = useChartConfigs();

const hasCategories = computed(() => {
  return Object.keys(props.data.categories).length > 0;
});

const chartData = computed(() => {
  const categories = Object.keys(props.data.categories).slice(0, 10);

  return categories.map((cat, idx) => ({
    name: cat,
    value: props.data.categories[cat],
    color: COLORS.categoryPalette[idx % COLORS.categoryPalette.length]
  }));
});

const config = computed(() => getCategoryConfig());
</script>

<style scoped>
.no-data {
  text-align: center;
  padding: 40px;
  color: #999;
}
</style>

// src/components/charts/CategoryChart.jsx
import React, { useMemo } from 'react';
import Chart from 'react-apexcharts';
import { useChartConfigs } from '../../hooks/useChartConfigs';

function CategoryChart({ data }) {
  const { getCategoryOptions } = useChartConfigs();

  const chartData = useMemo(() => {
    if (!data || !data.categories || Object.keys(data.categories).length === 0) {
      return null;
    }

    const categories = Object.keys(data.categories).slice(0, 10);
    const amounts = categories.map(c => data.categories[c]);
    const total = amounts.reduce((a, b) => a + b, 0);

    const options = {
      ...getCategoryOptions(),
      labels: categories,
      plotOptions: {
        pie: {
          donut: {
            labels: {
              show: true,
              total: {
                show: true,
                label: 'Total Expenses',
                formatter: () => `$${total.toFixed(0)}`
              }
            }
          }
        }
      }
    };

    return { options, series: amounts };
  }, [data, getCategoryOptions]);

  if (!chartData) {
    return <p style={{ textAlign: 'center', padding: '40px', color: '#999' }}>No expense categories found</p>;
  }

  return (
    <Chart
      options={chartData.options}
      series={chartData.series}
      type="donut"
      height={380}
    />
  );
}

export default CategoryChart;
